name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        script: |
          cd ~/my-node-app
          git pull origin main
          npm install
          # PM2 starts the app or restarts it if it is already running
          pm2 restart app || pm2 start index.js --name "app"
